#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cargo
# autospec version: v21
# autospec commit: 0698adb
#
Name     : bottom
Version  : 0.10.2
Release  : 1
URL      : https://github.com/ClementTsang/bottom/archive/refs/tags/0.10.2.tar.gz
Source0  : https://github.com/ClementTsang/bottom/archive/refs/tags/0.10.2.tar.gz
Source1  : http://localhost/cgit/vendor/bottom/snapshot/bottom-2025-01-03-00-54-52.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : 0BSD Apache-2.0 BSD-2-Clause BSL-1.0 HPND ICU MIT MPL-2.0 Unicode-DFS-2016 Unlicense Zlib
Requires: bottom-bin = %{version}-%{release}
Requires: bottom-license = %{version}-%{release}
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<div align="center">
<h1>bottom (btm)</h1>
<p>
A customizable cross-platform graphical process/system monitor for the terminal.<br />Supports Linux, macOS, and Windows. Inspired by <a href=https://github.com/aksakalli/gtop>gtop</a>, <a href=https://github.com/xxxserxxx/gotop>gotop</a>, and <a href=https://github.com/htop-dev/htop/>htop</a>.
</p>

%package bin
Summary: bin components for the bottom package.
Group: Binaries
Requires: bottom-license = %{version}-%{release}

%description bin
bin components for the bottom package.


%package license
Summary: license components for the bottom package.
Group: Default

%description license
license components for the bottom package.


%prep
%setup -q -n bottom-0.10.2
cd %{_builddir}
tar xf %{_sourcedir}/bottom-2025-01-03-00-54-52.tar.gz
cd %{_builddir}/bottom-0.10.2
mkdir -p ./vendor
cp -r %{_builddir}/bottom-2025-01-03-00-54-52/* %{_builddir}/bottom-0.10.2/./vendor
mkdir -p .cargo
echo '[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cargo build --release

%install
mkdir -p %{buildroot}/usr/share/package-licenses/bottom
cp %{_builddir}/bottom-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/bottom/a8ecc90bc0ce3f4b347e7a50bc1124d9bcfb95b1 || :
cp %{_builddir}/bottom-%{version}/wix/License.rtf %{buildroot}/usr/share/package-licenses/bottom/ad17f8d718ee5bcd3a09a77a9e3770902ce213d8 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/addr2line/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/addr2line/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9b76a43221967e5c55c4183406e1ebc7417da61d || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/adler/LICENSE-0BSD %{buildroot}/usr/share/package-licenses/bottom/3aedaafe8ea8fce424d1df3be32d1b8816944e0e || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/adler/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/1d47c63586fe3be7f228cff1ab0c029b53741875 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/adler/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ahash/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ahash/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/2646b6d2453275031022ab245a3a6d5da4ba80b2 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/bottom/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/bottom/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/allocator-api2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/96c0ace4eb1b0a78134d978d3c6d656a860a670f || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anstream/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anstream/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anstyle-parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anstyle-parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/64a8c11fd0f3068e743bfc681bcbef4f50a6b779 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anstyle-query/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anstyle-query/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anstyle-wincon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anstyle-wincon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/33dbd2d99ad231460bbb01812a52c85e577bd9ba || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anyhow/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/anyhow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/assert_cmd/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/assert_cmd/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/backtrace/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/backtrace/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/base64/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/base64/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/bitflags-1.3.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/bitflags-1.3.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/bstr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/bstr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/99b5dc64e06bf0354ef3baac0ea25c929e4e3a9a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/bstr/src/unicode/data/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/bottom/c4f8de16c29dc84a94d610b716fb1c9c7f143582 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/byteorder/COPYING %{buildroot}/usr/share/package-licenses/bottom/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/byteorder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/byteorder/UNLICENSE %{buildroot}/usr/share/package-licenses/bottom/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/cargo-husky/LICENSE.txt %{buildroot}/usr/share/package-licenses/bottom/caf0a1cf038e9e80e1224686bf8526c0c6d68660 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/cassowary/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/8205a96107bd2d30b9a078adcc9eea1bf5eccaf7 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/cassowary/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/86839b96a62723c6b7892a01b25908ff0c108447 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/castaway/LICENSE %{buildroot}/usr/share/package-licenses/bottom/fd33e0d46674b32eb66a5f1134e8d8a2d2f684c9 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/cfg_aliases-0.1.1/LICENSE %{buildroot}/usr/share/package-licenses/bottom/39806df76979277073594a0c19005c3c7fb17221 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/cfg_aliases/LICENSE %{buildroot}/usr/share/package-licenses/bottom/39806df76979277073594a0c19005c3c7fb17221 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_complete/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_complete/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_complete_fig/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_complete_fig/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_complete_nushell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_complete_nushell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4429d26c1ce0135d15ffd55ac21eed3854c69120 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_mangen/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/clap_mangen/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/18475316845fb3cc66bbe9d9f0cb6e86142afea2 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/colorchoice/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/colorchoice/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/compact_str/LICENSE %{buildroot}/usr/share/package-licenses/bottom/5c59637187123fdaf921408bc38718e196e5ee9a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/concat-string/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/concat-string/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/66f548e466ec88a6df6f8eb0bd06170e31f664bb || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/core-foundation-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/core-foundation-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/6c2945f449081ab19640fb7c70a081a1a4559399 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/core-foundation/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/core-foundation/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/6c2945f449081ab19640fb7c70a081a1a4559399 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/crossbeam-deque/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/crossbeam-deque/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/crossbeam-epoch/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/crossbeam-epoch/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/crossterm/LICENSE %{buildroot}/usr/share/package-licenses/bottom/94600bc2fcc5ecceeef40cd26c8c04d09f7d86fd || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/crossterm_winapi/LICENSE %{buildroot}/usr/share/package-licenses/bottom/94600bc2fcc5ecceeef40cd26c8c04d09f7d86fd || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ctrlc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/8bec88444202e13c35f17f3057132e6a21c287c1 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ctrlc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/darling/LICENSE %{buildroot}/usr/share/package-licenses/bottom/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/darling_core/LICENSE %{buildroot}/usr/share/package-licenses/bottom/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/darling_macro/LICENSE %{buildroot}/usr/share/package-licenses/bottom/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/deranged/LICENSE-Apache %{buildroot}/usr/share/package-licenses/bottom/13f55d9b7b3a769d76eab5d4a096f7ff24a017be || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/deranged/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ffffe83fef2bd6576c95e851bc81e1f6a641d638 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/dirs-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/43a3a49bd7af636c923a5ae475395b8e29320529 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/dirs-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/cf762fa3609793d5639ba9e1cbd254db276f50d3 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/dirs/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/43a3a49bd7af636c923a5ae475395b8e29320529 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/dirs/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/cf762fa3609793d5639ba9e1cbd254db276f50d3 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/doc-comment/LICENSE %{buildroot}/usr/share/package-licenses/bottom/e8d664ba1298bde0a80494159e28f62666b78824 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/downcast-rs/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/downcast-rs/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/2b8224e60ac628852fcda542a2a3ae0b3354123f || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/dyn-clone/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/dyn-clone/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/either/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/either/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/enum-as-inner/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/enum-as-inner/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/c71b43677c4ac8205f6eb573a073ea8e6df60c91 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/equivalent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/equivalent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/c371f0a7cbb203643d88566665a452f96bf1ab86 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/errno/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/errno/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/7a842f34e127456338641b14c7a00ec246d89fb6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/fern/LICENSE %{buildroot}/usr/share/package-licenses/bottom/b7210669edc9f343059ca20b6a02f6d934da2931 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/float-cmp/LICENSE %{buildroot}/usr/share/package-licenses/bottom/82c40cb8ef2b20a67619649a63762bebfe711480 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/fnv/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/fnv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/gimli/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/gimli/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/heck-0.4.1/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/heck-0.4.1/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/humantime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/humantime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ff432d95fdfee3587e45abd61685c2209d245901 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ident_case/LICENSE %{buildroot}/usr/share/package-licenses/bottom/218fc8c15534e8840cbff5801582c450c97869ab || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/indexmap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/indexmap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/7e5936a6fa3cf3518c01cec41345adf27399fe12 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ioctl-rs/LICENSE %{buildroot}/usr/share/package-licenses/bottom/cc17a68a18e4a5992a1f67a57c49855b9cfd444c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/is_terminal_polyfill/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/is_terminal_polyfill/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/itertools/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/itertools/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/lazycell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/lazycell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/bce2ed71de8bb33db2d29a5fcadd7407824e9248 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/libloading/LICENSE %{buildroot}/usr/share/package-licenses/bottom/4ad37fc99fecc5cda018043361f5b12e350e4052 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/libredox/LICENSE %{buildroot}/usr/share/package-licenses/bottom/f5a7ee42dcefea5415e6af50baca4e0c338bd8fe || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/linux-raw-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/linux-raw-sys/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/bottom/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/linux-raw-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/lru/LICENSE %{buildroot}/usr/share/package-licenses/bottom/9646201d104be96a96cfd1a632fb960e1da7a2d2 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/mach2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/mach2/LICENSE-BSD %{buildroot}/usr/share/package-licenses/bottom/24b715e62cdfc7753030f43432f6dd229d136c25 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/mach2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/21ecd644e03f61f0d9f8ee3bcc5c207435ff60ca || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/memchr/COPYING %{buildroot}/usr/share/package-licenses/bottom/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/bottom/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/bottom/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/miniz_oxide/LICENSE %{buildroot}/usr/share/package-licenses/bottom/18d7fe3c54698817feec1f2e04a9d5a0f046a80c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/miniz_oxide/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/bottom/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/miniz_oxide/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/bottom/18d7fe3c54698817feec1f2e04a9d5a0f046a80c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/miniz_oxide/LICENSE-ZLIB.md %{buildroot}/usr/share/package-licenses/bottom/11f0f1bee61ba6393c3dc7aefee7b92b604ff6c0 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/mio/LICENSE %{buildroot}/usr/share/package-licenses/bottom/27541df8e6d877c3912bbe4c48711f36e826cc5b || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/nix-0.25.1/LICENSE %{buildroot}/usr/share/package-licenses/bottom/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/nix-0.28.0/LICENSE %{buildroot}/usr/share/package-licenses/bottom/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/nix/LICENSE %{buildroot}/usr/share/package-licenses/bottom/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/normalize-line-endings/LICENSE %{buildroot}/usr/share/package-licenses/bottom/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ntapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/95606c72511bbbbeeecbdb16101d614a4680e622 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ntapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/6dd934749d3a64b9990030d688a6b3b17ad1004d || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/num-conv/LICENSE-Apache %{buildroot}/usr/share/package-licenses/bottom/c54e008a9d57391b98e60b14c8dc524acd7b2df9 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/num-conv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/18f13b198a4a6248c4ce96a0f82de708bc68fd0c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/num_threads/LICENSE-Apache %{buildroot}/usr/share/package-licenses/bottom/d7922ed0153e53eb7d63ea3fcae1040472c67679 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/num_threads/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/31e133ad6e12ed607bafa6decc49865e76e2a8e0 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/object/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/object/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/dd2f4bd6d87fe2780fc8e4135ce7dac6ff0b33ee || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/option-ext/LICENSE.txt %{buildroot}/usr/share/package-licenses/bottom/8fcc05c0dd9d9c76e948120c9520e4cbe85fb527 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/paste/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/paste/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/pin-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/a2f60339450a52e61c6c1e27dc44bd1e671ad28e || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/pin-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/91abce61ea0c1c313bb5ba31f04196490960a479 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/plist/LICENCE %{buildroot}/usr/share/package-licenses/bottom/9e6854bcd4c4036a8d9dc5138e85ba9db953d05f || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/portable-pty/LICENSE.md %{buildroot}/usr/share/package-licenses/bottom/e28fa3ae908c87c18fc2d7ffea18afdf1bc8ca27 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/powerfmt/LICENSE-Apache %{buildroot}/usr/share/package-licenses/bottom/2ef5dbf415191a7880f5baa5ab1997a807967c13 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/powerfmt/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/5641ab41a62889b9a22161d95f174fc889dd9660 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/predicates-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/predicates-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/predicates-tree/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/predicates-tree/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/predicates/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/predicates/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/quick-xml/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/bottom/dc5a1036298990ac083baa9bf95f6a1b8ee98c0f || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ratatui/LICENSE %{buildroot}/usr/share/package-licenses/bottom/51386ae5a11a72e05db629d63588c9f1cfda8d1e || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rayon-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rayon-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rayon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rayon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/bottom/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/redox_users/LICENSE %{buildroot}/usr/share/package-licenses/bottom/c56bd0668edca4d06b6cd881d4d2839da53058cd || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/bottom/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/roff/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/roff/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rustc-demangle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rustc-demangle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rustix/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rustix/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/bottom/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rustix/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rustversion/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/rustversion/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/bottom/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/same-file/COPYING %{buildroot}/usr/share/package-licenses/bottom/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/same-file/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/same-file/UNLICENSE %{buildroot}/usr/share/package-licenses/bottom/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/schemars/LICENSE %{buildroot}/usr/share/package-licenses/bottom/ce343928dd1d98a7d25f044bd77fc4d5b9959e1b || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/schemars_derive/LICENSE %{buildroot}/usr/share/package-licenses/bottom/ce343928dd1d98a7d25f044bd77fc4d5b9959e1b || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serde_derive_internals/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serde_derive_internals/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serde_spanned/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serde_spanned/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serial-core/LICENSE %{buildroot}/usr/share/package-licenses/bottom/cc17a68a18e4a5992a1f67a57c49855b9cfd444c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/serial-unix/LICENSE %{buildroot}/usr/share/package-licenses/bottom/cc17a68a18e4a5992a1f67a57c49855b9cfd444c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/shared_library/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/ea4215a6204b8414db6209c378a78a2dfb91c9ee || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/shared_library/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/84cdc425af0f0bd3ea1da82e503b37fe0178263b || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/shell-words/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/84f97e99da641fa412ca16f122dc89274964bc46 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/shell-words/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/def480ff8f0d4c1c67eb30ba7bd22250b4f98b91 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/signal-hook-mio/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/signal-hook-mio/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/8e31d76c1073644a6e761836ac34a590fee47a83 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/signal-hook-registry/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/signal-hook-registry/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/8e31d76c1073644a6e761836ac34a590fee47a83 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/signal-hook/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/signal-hook/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/8e31d76c1073644a6e761836ac34a590fee47a83 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/stability/LICENSE %{buildroot}/usr/share/package-licenses/bottom/1d221033bed396c313ab3ae2c464aecc7802c971 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/static_assertions/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/static_assertions/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/972723ef8f594b1c7515e4c227ff9d5912041fac || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/strsim/LICENSE %{buildroot}/usr/share/package-licenses/bottom/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/strum/LICENSE %{buildroot}/usr/share/package-licenses/bottom/967573fc64a706430e19b4942fe728870c8182f8 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/strum_macros/LICENSE %{buildroot}/usr/share/package-licenses/bottom/967573fc64a706430e19b4942fe728870c8182f8 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/sysctl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/113ef81b9b6ef59c88b073449bcdec7faba6e57a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/sysinfo/LICENSE %{buildroot}/usr/share/package-licenses/bottom/f83864fda2a313306dfb3de8b01a36830a057a46 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/terminal_size/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/terminal_size/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/e08d1736c80198e1adec92ff27482e7abbc42d86 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/termios/LICENSE %{buildroot}/usr/share/package-licenses/bottom/cc17a68a18e4a5992a1f67a57c49855b9cfd444c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/termtree/LICENSE %{buildroot}/usr/share/package-licenses/bottom/19b4f6d5815ac866d69353dd925e66db58a24a77 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/thiserror-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/thiserror-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/thiserror/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/thiserror/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/time-core/LICENSE-Apache %{buildroot}/usr/share/package-licenses/bottom/13f55d9b7b3a769d76eab5d4a096f7ff24a017be || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/time-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ffffe83fef2bd6576c95e851bc81e1f6a641d638 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/time-macros/LICENSE-Apache %{buildroot}/usr/share/package-licenses/bottom/75b9500512bb4d24722887e64a982c51e6bdcc4c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/time-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/03431277c040357c85596083ac918eb591ac04ac || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/time/LICENSE-Apache %{buildroot}/usr/share/package-licenses/bottom/75b9500512bb4d24722887e64a982c51e6bdcc4c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/time/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/03431277c040357c85596083ac918eb591ac04ac || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/toml_datetime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/toml_datetime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/toml_edit/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/toml_edit/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/typenum/LICENSE %{buildroot}/usr/share/package-licenses/bottom/481e4be7d70c11ee3f6e04a59a0e5afccc551db2 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/typenum/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/69facfd64b2a7aa4a22c917ef10cd96e41b75b87 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/typenum/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/5984f5244c7bc13bf15a5bea823c04ec0bbc714f || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-ellipsis/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-ellipsis/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/1a513f59f66c4a218a367ec5bc26c3ed4150abd7 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/bottom/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-segmentation/COPYRIGHT %{buildroot}/usr/share/package-licenses/bottom/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-segmentation/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-segmentation/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-truncate/COPYRIGHT %{buildroot}/usr/share/package-licenses/bottom/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-truncate/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-truncate/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/8c8867dbe260a6b77229621a8f55979f7d92ec95 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-width/COPYRIGHT %{buildroot}/usr/share/package-licenses/bottom/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-width/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/unicode-width/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/uom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/e3778f97945d358058eb8f40841c96d0463848bd || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/utf8parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/utf8parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/93074692b8a28bef1743c44a9e5b97b1401c0d09 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/wait-timeout/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/wait-timeout/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/walkdir/COPYING %{buildroot}/usr/share/package-licenses/bottom/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/walkdir/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/walkdir/UNLICENSE %{buildroot}/usr/share/package-licenses/bottom/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/bottom/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/winapi-util/COPYING %{buildroot}/usr/share/package-licenses/bottom/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/winapi-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/winapi-util/UNLICENSE %{buildroot}/usr/share/package-licenses/bottom/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/2243f7a86daaa727d34d92e987a741036f288464 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-0.52.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-0.52.0/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-core-0.52.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-core-0.52.0/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-core/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-core/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-implement/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-implement/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-interface/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-interface/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-result/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-result/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-strings/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-strings/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-sys-0.48.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-sys-0.48.0/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-targets-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-targets-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_aarch64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_aarch64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_aarch64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_aarch64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_i686_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_i686_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_i686_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_i686_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/winnow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/c0955b5351b1dcafdd0b9bb2d7e84fe0e3d731ca || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/winreg/LICENSE %{buildroot}/usr/share/package-licenses/bottom/e952409591eb40fe31b1e43ab9bf11d27000a9c0 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/wrapcenum-derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/b6c39038a6c6399070199d86249c50a6774ca1c3 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/wrapcenum-derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/082abb1078b3e148973a2d0ebda778a2c2e728ae || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/zerocopy-derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/zerocopy-derive/LICENSE-BSD %{buildroot}/usr/share/package-licenses/bottom/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/zerocopy-derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/zerocopy/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/ebbc0758a0322f1bfe28f5438867a084e53941c8 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/zerocopy/LICENSE-BSD %{buildroot}/usr/share/package-licenses/bottom/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1 || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/zerocopy/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/zerocopy/src/third_party/rust/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/bottom-2025-01-03-00-54-52/zerocopy/src/third_party/rust/LICENSE-MIT %{buildroot}/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cargo install --path .
mkdir -p %{buildroot}/usr/bin
pushd "${HOME}/.cargo/bin/"
mv * %{buildroot}/usr/bin/
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/btm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bottom/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/bottom/03431277c040357c85596083ac918eb591ac04ac
/usr/share/package-licenses/bottom/082abb1078b3e148973a2d0ebda778a2c2e728ae
/usr/share/package-licenses/bottom/113ef81b9b6ef59c88b073449bcdec7faba6e57a
/usr/share/package-licenses/bottom/11f0f1bee61ba6393c3dc7aefee7b92b604ff6c0
/usr/share/package-licenses/bottom/13f55d9b7b3a769d76eab5d4a096f7ff24a017be
/usr/share/package-licenses/bottom/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/bottom/18475316845fb3cc66bbe9d9f0cb6e86142afea2
/usr/share/package-licenses/bottom/18d7fe3c54698817feec1f2e04a9d5a0f046a80c
/usr/share/package-licenses/bottom/18f13b198a4a6248c4ce96a0f82de708bc68fd0c
/usr/share/package-licenses/bottom/19b4f6d5815ac866d69353dd925e66db58a24a77
/usr/share/package-licenses/bottom/1a513f59f66c4a218a367ec5bc26c3ed4150abd7
/usr/share/package-licenses/bottom/1d221033bed396c313ab3ae2c464aecc7802c971
/usr/share/package-licenses/bottom/1d47c63586fe3be7f228cff1ab0c029b53741875
/usr/share/package-licenses/bottom/218fc8c15534e8840cbff5801582c450c97869ab
/usr/share/package-licenses/bottom/21ecd644e03f61f0d9f8ee3bcc5c207435ff60ca
/usr/share/package-licenses/bottom/2243f7a86daaa727d34d92e987a741036f288464
/usr/share/package-licenses/bottom/24b715e62cdfc7753030f43432f6dd229d136c25
/usr/share/package-licenses/bottom/2646b6d2453275031022ab245a3a6d5da4ba80b2
/usr/share/package-licenses/bottom/27541df8e6d877c3912bbe4c48711f36e826cc5b
/usr/share/package-licenses/bottom/2ad1215c12bd0a3492399dc438aa63084323c662
/usr/share/package-licenses/bottom/2b8224e60ac628852fcda542a2a3ae0b3354123f
/usr/share/package-licenses/bottom/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/bottom/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/bottom/2ef5dbf415191a7880f5baa5ab1997a807967c13
/usr/share/package-licenses/bottom/31e133ad6e12ed607bafa6decc49865e76e2a8e0
/usr/share/package-licenses/bottom/33dbd2d99ad231460bbb01812a52c85e577bd9ba
/usr/share/package-licenses/bottom/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/bottom/39806df76979277073594a0c19005c3c7fb17221
/usr/share/package-licenses/bottom/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/bottom/3aedaafe8ea8fce424d1df3be32d1b8816944e0e
/usr/share/package-licenses/bottom/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/bottom/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/bottom/43a3a49bd7af636c923a5ae475395b8e29320529
/usr/share/package-licenses/bottom/4429d26c1ce0135d15ffd55ac21eed3854c69120
/usr/share/package-licenses/bottom/46aace8adc5b06990d9ee2b6bd555ea03c4df7a1
/usr/share/package-licenses/bottom/481e4be7d70c11ee3f6e04a59a0e5afccc551db2
/usr/share/package-licenses/bottom/493b3ee6eb0b5b24708a0a07ab11ad2bc1b49c9c
/usr/share/package-licenses/bottom/4ad37fc99fecc5cda018043361f5b12e350e4052
/usr/share/package-licenses/bottom/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/bottom/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/bottom/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a
/usr/share/package-licenses/bottom/51386ae5a11a72e05db629d63588c9f1cfda8d1e
/usr/share/package-licenses/bottom/5641ab41a62889b9a22161d95f174fc889dd9660
/usr/share/package-licenses/bottom/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/bottom/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/bottom/5984f5244c7bc13bf15a5bea823c04ec0bbc714f
/usr/share/package-licenses/bottom/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/bottom/5c59637187123fdaf921408bc38718e196e5ee9a
/usr/share/package-licenses/bottom/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/bottom/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
/usr/share/package-licenses/bottom/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/bottom/64a8c11fd0f3068e743bfc681bcbef4f50a6b779
/usr/share/package-licenses/bottom/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/bottom/66f548e466ec88a6df6f8eb0bd06170e31f664bb
/usr/share/package-licenses/bottom/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/bottom/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/bottom/69facfd64b2a7aa4a22c917ef10cd96e41b75b87
/usr/share/package-licenses/bottom/6c2945f449081ab19640fb7c70a081a1a4559399
/usr/share/package-licenses/bottom/6dd934749d3a64b9990030d688a6b3b17ad1004d
/usr/share/package-licenses/bottom/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/bottom/75b9500512bb4d24722887e64a982c51e6bdcc4c
/usr/share/package-licenses/bottom/7a842f34e127456338641b14c7a00ec246d89fb6
/usr/share/package-licenses/bottom/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/bottom/7e5936a6fa3cf3518c01cec41345adf27399fe12
/usr/share/package-licenses/bottom/8205a96107bd2d30b9a078adcc9eea1bf5eccaf7
/usr/share/package-licenses/bottom/82c40cb8ef2b20a67619649a63762bebfe711480
/usr/share/package-licenses/bottom/84cdc425af0f0bd3ea1da82e503b37fe0178263b
/usr/share/package-licenses/bottom/84f97e99da641fa412ca16f122dc89274964bc46
/usr/share/package-licenses/bottom/86839b96a62723c6b7892a01b25908ff0c108447
/usr/share/package-licenses/bottom/8bec88444202e13c35f17f3057132e6a21c287c1
/usr/share/package-licenses/bottom/8c8867dbe260a6b77229621a8f55979f7d92ec95
/usr/share/package-licenses/bottom/8e31d76c1073644a6e761836ac34a590fee47a83
/usr/share/package-licenses/bottom/8fcc05c0dd9d9c76e948120c9520e4cbe85fb527
/usr/share/package-licenses/bottom/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/bottom/91abce61ea0c1c313bb5ba31f04196490960a479
/usr/share/package-licenses/bottom/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/bottom/93074692b8a28bef1743c44a9e5b97b1401c0d09
/usr/share/package-licenses/bottom/94600bc2fcc5ecceeef40cd26c8c04d09f7d86fd
/usr/share/package-licenses/bottom/95606c72511bbbbeeecbdb16101d614a4680e622
/usr/share/package-licenses/bottom/9646201d104be96a96cfd1a632fb960e1da7a2d2
/usr/share/package-licenses/bottom/967573fc64a706430e19b4942fe728870c8182f8
/usr/share/package-licenses/bottom/96c0ace4eb1b0a78134d978d3c6d656a860a670f
/usr/share/package-licenses/bottom/972723ef8f594b1c7515e4c227ff9d5912041fac
/usr/share/package-licenses/bottom/99b5dc64e06bf0354ef3baac0ea25c929e4e3a9a
/usr/share/package-licenses/bottom/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/bottom/9b76a43221967e5c55c4183406e1ebc7417da61d
/usr/share/package-licenses/bottom/9e6854bcd4c4036a8d9dc5138e85ba9db953d05f
/usr/share/package-licenses/bottom/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/bottom/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/bottom/a2f60339450a52e61c6c1e27dc44bd1e671ad28e
/usr/share/package-licenses/bottom/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/bottom/a6fe1503554eb18138838c526d150f58fc104133
/usr/share/package-licenses/bottom/a8ecc90bc0ce3f4b347e7a50bc1124d9bcfb95b1
/usr/share/package-licenses/bottom/ad17f8d718ee5bcd3a09a77a9e3770902ce213d8
/usr/share/package-licenses/bottom/b6c39038a6c6399070199d86249c50a6774ca1c3
/usr/share/package-licenses/bottom/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2
/usr/share/package-licenses/bottom/b7210669edc9f343059ca20b6a02f6d934da2931
/usr/share/package-licenses/bottom/bce2ed71de8bb33db2d29a5fcadd7407824e9248
/usr/share/package-licenses/bottom/c0955b5351b1dcafdd0b9bb2d7e84fe0e3d731ca
/usr/share/package-licenses/bottom/c371f0a7cbb203643d88566665a452f96bf1ab86
/usr/share/package-licenses/bottom/c4f8de16c29dc84a94d610b716fb1c9c7f143582
/usr/share/package-licenses/bottom/c54e008a9d57391b98e60b14c8dc524acd7b2df9
/usr/share/package-licenses/bottom/c56bd0668edca4d06b6cd881d4d2839da53058cd
/usr/share/package-licenses/bottom/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/bottom/c71b43677c4ac8205f6eb573a073ea8e6df60c91
/usr/share/package-licenses/bottom/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/bottom/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/bottom/caf0a1cf038e9e80e1224686bf8526c0c6d68660
/usr/share/package-licenses/bottom/cc1662c1ffded2451f1b822c62ec085862bd5816
/usr/share/package-licenses/bottom/cc17a68a18e4a5992a1f67a57c49855b9cfd444c
/usr/share/package-licenses/bottom/ce343928dd1d98a7d25f044bd77fc4d5b9959e1b
/usr/share/package-licenses/bottom/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/bottom/cf762fa3609793d5639ba9e1cbd254db276f50d3
/usr/share/package-licenses/bottom/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/bottom/d7922ed0153e53eb7d63ea3fcae1040472c67679
/usr/share/package-licenses/bottom/dc5a1036298990ac083baa9bf95f6a1b8ee98c0f
/usr/share/package-licenses/bottom/dd2f4bd6d87fe2780fc8e4135ce7dac6ff0b33ee
/usr/share/package-licenses/bottom/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/bottom/def480ff8f0d4c1c67eb30ba7bd22250b4f98b91
/usr/share/package-licenses/bottom/e08d1736c80198e1adec92ff27482e7abbc42d86
/usr/share/package-licenses/bottom/e28fa3ae908c87c18fc2d7ffea18afdf1bc8ca27
/usr/share/package-licenses/bottom/e3778f97945d358058eb8f40841c96d0463848bd
/usr/share/package-licenses/bottom/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/bottom/e8d664ba1298bde0a80494159e28f62666b78824
/usr/share/package-licenses/bottom/e952409591eb40fe31b1e43ab9bf11d27000a9c0
/usr/share/package-licenses/bottom/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/bottom/ea4215a6204b8414db6209c378a78a2dfb91c9ee
/usr/share/package-licenses/bottom/ebbc0758a0322f1bfe28f5438867a084e53941c8
/usr/share/package-licenses/bottom/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/bottom/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/bottom/f5a7ee42dcefea5415e6af50baca4e0c338bd8fe
/usr/share/package-licenses/bottom/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/bottom/f83864fda2a313306dfb3de8b01a36830a057a46
/usr/share/package-licenses/bottom/f911b0506e6ba6a56b4edac717b461799f380ef0
/usr/share/package-licenses/bottom/fd33e0d46674b32eb66a5f1134e8d8a2d2f684c9
/usr/share/package-licenses/bottom/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
/usr/share/package-licenses/bottom/ff432d95fdfee3587e45abd61685c2209d245901
/usr/share/package-licenses/bottom/ffffe83fef2bd6576c95e851bc81e1f6a641d638
